### ISSUE TITLE
[Good first issue]: Broken link in PR template.

### ISSUE THREAD

**Issue by yardasol** [arfc/arfc.github.io#234] opened 2021-10-22 18:06 UTC
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

## Expected Behavior
The PR template has a functioning link to [the page on the group website for reviewing pull requests](https://arfc.github.io/manual/guides/pull_requests).

## Actual Behavior
The PR template has a broken link this page. In fact it doesn't even leave github.

## Steps to Reproduce the Problem
  1. Look at any of the [recent PRs](https://github.com/arfc/arfc.github.io/pulls?q=is%3Apr+is%3Aclosed), or the [PR template](https://github.com/arfc/arfc.github.io/blob/source/.github/pull_request_template.md) directly.
  2. Click on the link at the bottom

> Reviewers should use this link to get to the Review Checklist before they begin their review.

  3. You should obsever the Actual Behavior described above

## Specifications

  - Version: Firefox 93.0
  - Platform: Ubuntu 21.04

## How can this issue be closed?
This issue can be closed when the link in the PR template follows the Expected Behavior.

**Comment by nsryan2** [comment] 2021-11-02 23:10
I don't know if this was addressed in a pr and not closed, but I am not able to reproduce this issue. Is it possible that you were looking at the version of the site that takes longer to update? You can reach the site at `arfc.github.io` or at `arfc.npre.illinois.edu`

**Comment by samgdotson** [comment] 2022-10-20 20:52
@hwacc-y Have a crack at it, nicholas!

**Closed** 2023-03-01 20:36 UTC
Labels: Comp:Analysis, Difficulty:1-Beginner, Priority:1-Critical, Status:1-New, Type:Bug
